name: Playwright Tests

on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60

    runs-on: ubuntu-latest

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Yarn
        run: npm install -g yarn

      - name: Instalar dependências
        run: yarn install

      - name: Instalar browsers do Playwright
        run: yarn playwright install --with-deps

      - name: Instalar dependências da API
        run: |
          cd apps/api
          yarn install

      - name: Criar banco
        run: |
          cd apps/api
          yarn db:init

      - name: Subir API
        run: |
          cd apps/api
          yarn dev &
      
      - name: Subir Frontend
        run: |
          cd apps/web
          yarn dev &

      - name: Esperar aplicação iniciar
        run: npx wait-on http://localhost:8080

      - name: Rodar testes
        run: yarn playwright test

      - name: Upload relatório
        uses: actions/upload-artifact@v4

        if: ${{ !cancelled() }}

        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30